# ============================================================================ #
#                          U p d a t e   R e a d m e   a n d   S t a t s
# ============================================================================ #

name: Update Readme and Stats

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 4 * * *"
  workflow_dispatch:

# ============================================================================ #
#                                   J o b s
# ============================================================================ #

jobs:
  # -------------------------------------------------------------------------- #
  #                                R e a d m e
  # -------------------------------------------------------------------------- #
  readme:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest

    steps:
      # Step 1: C h e c k o u t   r e p o s i t o r y
      - uses: actions/checkout@v3

      # Step 2: G e n e r a t e   R e a d m e
      - name: Generate readme
        env:
          WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
        shell: pwsh
        run: . ./build-svg.ps1

      # Step 3: C o m m i t   c h a n g e s
      - name: Commit changes
        uses: EndBug/add-and-commit@v4
        with:
          author_name: Yuriy Gribanov
          author_email: yuriydevops@gmail.com
          message: "Auto updating my readme"
          add: "*.svg"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # -------------------------------------------------------------------------- #
  #                                S n a k e
  # -------------------------------------------------------------------------- #
  snake:
    runs-on: ubuntu-latest

    steps:
      # Step 1: G e n e r a t e   c o n t r i b u t i o n   s n a k e   S V G
      - name: Generate contribution snake SVG
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: gribanj
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      # Step 2: P u s h   s n a k e   S V G   t o   o u t p u t   b r a n c h
      - name: Push snake SVG to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # -------------------------------------------------------------------------- #
  #                        W a k a T i m e   S t a t s
  # -------------------------------------------------------------------------- #
  wakatime:
    if: github.actor != 'github-actions[bot]'
    name: Update WakaTime Stats
    runs-on: ubuntu-latest

    steps:
      # Step 1: U p d a t e   W a k a T i m e   s t a t s
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_LINES_OF_CODE: "True"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_COMMIT: "True"
          SHOW_DAYS_OF_WEEK: "True"
          SHOW_LANGUAGE: "True"
          SHOW_OS: "True"
          SHOW_PROJECTS: "False"
          SHOW_TIMEZONE: "False"
          SHOW_LANGUAGE_PER_REPO: "True"
          SHOW_SHORT_INFO: "True"
          SHOW_LOC_CHART: "False"
          LOCALE: en
