name: Update Readme

on:
  schedule:
    - cron: "0 4 * * *"
  workflow_dispatch:

jobs:
  readme:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Generate readme
        env:
          WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
        shell: pwsh
        run: . ./build-svg.ps1

      - name: Commit changes
        uses: EndBug/add-and-commit@v4
        with:
          author_name: Yuriy Gribanov
          author_email: yuriydevops@gmail.com
          message: "Auto updating my readme"
          add: "*.svg"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
